import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import "./assets/styles/tailwind.css";
import "./assets/styles/global.css";
import { importGlobal } from "./utils/index";
const app = createApp(App);
app.use(router);
importGlobal(app);
app.mount("#app");
